### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "dezember2023@ohms.de",
    "password": "_IKnowYourFate_"
}

### sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "dezember2023@ohms.de",
    "password": "_IKnowYourFate_"
}

###

GET http://localhost:3000/auth

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=ohne@nicht.de

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "password": "test"
}

### Delete a user given id
DELETE  http://localhost:3000/auth/2